- .dockerignore
- README.md
- docker/Dockerfile
- scripts/install.trtis_client.sh
Closes #64 
```shell script
docker pull mlmodelci/mlmodelci
```
N.A.
Faster installation, system ignorant, TensorRT support.
Yes, already updated.
> [doc] 🐋 Docker environment support

- README.md
> [doc] fix readme typo

- README.md
> [doc] add some words

- README.md
- modelci/controller/controller.py
> [feature] profile callback

- README.md
- docs/tutorial/profile.md
- example/sample_mrcnn.py
- modelci/controller/controller.py
- modelci/hub/client/README.md
- modelci/hub/client/sample.py
- modelci/hub/profiler.py
- modelci/metrics/benchmark/metric.py
- requirements.txt
> [MRG] Profiling Controller

- modelci/types/bo/dynamic_profile_result_bo.py
- modelci/types/bo/model_objects.py
- modelci/types/bo/profile_result_bo.py
- modelci/types/do/dynamic_profile_result_do.py
- tests/test_model_service.py
Closes #81 
N.A.
Yes, profiling related @huangyz0918
> [fix] Update dynamic profile result attributes

- cli/ui.py
> [feat] Richful CLI

- modelci/hub/deployer/onnxs/deploy_model_cpu.sh
- modelci/hub/deployer/onnxs/deploy_model_gpu.sh
- modelci/hub/deployer/pytorch/deploy_model_cpu.sh
- modelci/hub/deployer/pytorch/deploy_model_gpu.sh
- modelci/hub/profiler.py
> 🚑  quickfix: Check docker server started or not before diagnosing.

- README.md
> [misc] update readme and add bib

- modelci/metrics/README.md
> revise metric roadmap

- README.md
> [misc] add news to readme

- modelci/hub/deployer/onnxs/deploy_model_gpu.sh
> [fix] ONNX GPU serving startup script

- CHANGELOG.md
- README.md
add changelog file for recording update information
Closes #
> add a CHANGELOG.md

- modelci/cli/__init__.py
Fix from https://github.com/cap-ntu/ML-Model-CI/issues/146#issuecomment-719108024
Fix #146
> [MRG] Fix cli import error

- CONTRIBUTING.md
> [MRG]Add contribution guide

- README.md
> :books: Update README

- README.md
> :books: Update README demo section

- README.md
> [misc] update demo images

- README.md
> [misc] introduce specific tools

- README.md
- docs/tutorial/register.md
- example/notebook/image_classification_model_deployment.ipynb
- example/notebook/object_detection_model_deployment.ipynb
- example/resnet50.yml
- example/resnet50_explicit_path.yml
- modelci/hub/converter.py
- modelci/hub/init_data.py
- modelci/hub/manager.py
- modelci/hub/utils.py
- modelci/persistence/model_dao.py
- modelci/persistence/service.py
- modelci/types/bo/__init__.py
- modelci/types/bo/model_bo.py
- modelci/types/bo/model_objects.py
- modelci/types/do/model_do.py
- tests/test_model_service.py
Closes #166 #167 
- add Metric and Task enum class, modify the parameters of `register_model` function
- add a `model_input` parameter enables users to use a self-defined model input tensor
- modify related usages in documents
Yes
> [MRG]:sparkles: Update register information (metric and task) and add an object detection example

- frontend/package-lock.json
- frontend/package.json
> :heavy_plus_sign: updating npm package

- example/notebook/object_detection_model_deployment.ipynb
- modelci/hub/converter.py
- modelci/hub/deployer/onnxs/environment.yml
- modelci/hub/manager.py
- modelci/types/bo/model_objects.py
Closes #176
since hummingbird has removes ONNX_INPUTS in current pr https://github.com/microsoft/hummingbird/pull/378,
we should remove this to avoid error.
No
> Modify detection notebook and save pytorch model

- frontend/README.md
- frontend/src/config.ts
- frontend/src/pages/Dashboard/index.tsx
- modelci/app/v1/endpoints/model.py
- modelci/env-backend.env
- modelci/types/vo/model_vo.py
Closes #178 
1. add icejs default port 3333 to env to address CORS related issues
2. introduce a config file for frontend project
3. make changes to fix model display issue due to recent database structure change.
4. enable display profile table for model without valid profiling data
Here is an example screenshot
Yes
> :bug: fix model display issue

- CONTRIBUTING.md
- environment.yml
- modelci/finetuner/README.md
- modelci/finetuner/__init__.py
- modelci/finetuner/cv_example.py
- modelci/finetuner/trainer.py
- pure_requires.yml
Try `python finetuner/cv_example.py`
Reference https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html#finetuning-the-convnet
New feature.
Yes.
> [MRG] Feat/trainer

- CONTRIBUTING.md
- environment.yml
- pure_requires.yml
Leave pytorch required packages to later manual installation
Closes #183 
`conda env create -f environemt.yml`
Later install the packages that require `torch`.
N.A.
Yes.
> [MRG] Fix conda environment

- modelci/finetuner/computer_vision_fine_tuning.py
- modelci/finetuner/torch_data_module.py
> Add fintune data module and  PyTorchLightning finetune example code

- .gitignore
- CONTRIBUTING.md
- README.md
- modelci/cli/model_cli.py
- scripts/setup_env.sh
> [MRG] [misc] fix installation issue and improve contributing.md

- modelci/app/experimental/endpoints/cv_tuner.py
- modelci/app/experimental/endpoints/trainer.py
- modelci/experimental/curd/model_train.py
- modelci/experimental/finetuner/trainer.py
- modelci/experimental/model/model_train.py
Start the frontend:
```
python -m uvicorn modelci.app.main:app --host 0.0.0.0
```
Try the POST training job API using `0.0.0.0/docs`:
Change the body as following:
```JSON
{
"model": "6012e189d102bac1594a9cdd",
"data_module": {
"dataset_name": "CIFAR10",
"batch_size": 256,
"num_workers": 6
},
"min_epochs": 1,
"max_epochs": 1,
"optimizer_type": "SGD",
"optimizer_property": {
"lr": 0.01
},
"lr_scheduler_type": "StepLR",
"lr_scheduler_property": {
"step_size": 6
},
"loss_function": "torch.nn.CrossEntropyLoss"
}
```
The training job is submitted and trained:
Approach: submit the training parameters -> create the training job by `PyTorchTrainer` -> run the training job immediately (to be run in a controller) -> see trained model (to be saved to DB)
New experimental features.
No.
> Add Training Job Generation and Get Job Runs

- CONTRIBUTING.md
- README.md
- README_zh_CN.md
- modelci/cli/__init__.py
- modelci/cli/model_cli.py
- modelci/cli/model_manager.py
- modelci/cli/modelci_service.py
Closes #202 
Test under my server.
has updated
`modelci service init` to start the service on a leader server
> [MRG][cli] update modelci service logic

- frontend/package.json
- frontend/src/pages/VersionTree/index.css
- frontend/src/pages/VersionTree/index.tsx
- frontend/src/pages/VersionTree/utils/mock.json
- frontend/src/pages/VersionTree/utils/type.tsx
- modelci/persistence/model_dao.py
- modelci/persistence/service.py
- modelci/types/do/model_do.py
> [MRG][frontend] slightly modify version tree

- .github/workflows/run_test.yml
- README.md
Closes #226 
The workflow script is tested, here is a successful run:
<https://github.com/univerone/ML-Model-CI/runs/1950020813>
Set the slack webhook URL  (see https://api.slack.com/incoming-webhooks) in repo secrets setting to keep it credential
> [MRG] 👷 add github action workflow

- CONTRIBUTING.md
- README.md
- modelci/config.py
Add setup environment after install
> [MRG] Update README.md

- .github/workflows/run_test.yml
- modelci/metrics/benchmark/metric.py
> 💚 [CI] fix github action

- README.md
> [MRG][misc] re-orgainize the main read me

- modelci/app/__init__.py
- modelci/app/main.py
Closes #
```
❯ python modelci/cli/__init__.py service init                                                                                                                                                                                          
2021-03-20 22:55:53,712 - ml-modelci Docker Container Manager - WARNING - Service already exist, found container name=gpu-metrics-exporter-39386.                                                                                      
2021-03-20 22:55:54,092 - ml-modelci Docker Container Manager - INFO - Service started.                                                                                                                                                
2021-03-20 22:55:54,092 - ml-modelci Docker Container Manager - WARNING - Service already …
```
> :beetle: Fix service init modelci backend not started

- modelci/app/main.py
Super minor PR, won't affect anything.
No.
> [MRG] 🔧 Move `uvicorn` to global import

- tests/test_keras_conversion.py
Closes #
I've already tested on my server.
> fix a small bug in keras conversion test

- modelci/hub/deployer/pytorch/environment.yml
- modelci/hub/deployer/pytorch/torch-serve-cpu.Dockerfile
- modelci/hub/deployer/pytorch/torch-serve-gpu.Dockerfile
Upgrade torch serving Docker image.
N.A.
No.
No.
> :arrow_up: [MRG] Upgrade torch-serving Docker

- example/resnet50.yml
- example/resnet50_explicit_path.yml
- modelci/app/experimental/endpoints/cv_tuner.py
- modelci/app/v1/endpoints/model.py
- modelci/cli/modelhub.py
- modelci/hub/converter/converter.py
- modelci/hub/model_loader.py
- modelci/hub/registrar.py
- modelci/hub/utils.py
- modelci/persistence/service_.py
- modelci/types/models/__init__.py
- modelci/types/models/common.py
- modelci/ui.py
- tests/test_modelhub_cli.py
> [MRG]Update modelhub cache file module
